FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libtool libssl-dev autoconf pkg-config

COPY . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
